# https://kubernetes.io/ja/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/
# https://kubernetes.io/ja/docs/tasks/configure-pod-container/share-process-namespace/

apiVersion: v1
kind: Pod
metadata:
  name: communication
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx:1.19.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html

  # kubectl attach -it communication -c alpine
  - name: alpine
    image: alpine:3.12.0
    command: ['/bin/sh']
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    stdin: true
    tty: true
    volumeMounts:
    - name: shared-volume
      mountPath: /work

  restartPolicy: Never
  volumes:
  - name: shared-volume
    emptyDir: {}
