apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx

  labels:
    app: nginx

    # https://kubernetes.io/ja/docs/concepts/overview/working-with-objects/common-labels/
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: sample-nginx01
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: sample-httpd

  annotations:
    hoge: hoge

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  # https://kubernetes.io/ja/docs/concepts/workloads/controllers/deployment/
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  revisionHistoryLimit: 10

  template:
    metadata:
      labels:
        app: nginx
    spec:

      # https://kubernetes.io/ja/docs/concepts/workloads/pods/init-containers/
      initContainers:
      - name: init-busybox
        image: busybox:1.32
        command: ['/bin/sh', '-c', 'echo hoge > /html/index.html']
        volumeMounts:
        - name: html
          mountPath: /html

      containers:
      - name: nginx
        image: nginx:1.19.2
        ports:
        - containerPort: 80

        # https://kubernetes.io/ja/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3

        # https://kubernetes.io/ja/docs/tasks/configure-pod-container/assign-memory-resource/
        # https://kubernetes.io/ja/docs/tasks/configure-pod-container/assign-cpu-resource/
        resources:
          limits:
            memory: "100Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "100m"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      restartPolicy: Always

      # https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
      volumes:
      - name: html
        emptyDir: {}

