apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

configMapGenerator:
- name: file-config
  files:
  - configfile
- name: literal-config
  literals:
  - KEY=VALUE

vars:
- name: DEPLOYMENT_NAME
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: busybox
  fieldref:
    fieldpath: metadata.name

