apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: production-

commonLabels:
  variant: production

commonAnnotations:
  variant: production

bases:
- ../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: busybox
  newName: busybox
  newTag: "1.32.0"
