apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

commonLabels:
  variant: staging

commonAnnotations:
  variant: staging

bases:
- ../../base

patchesStrategicMerge:
- configmap.yaml

images:
- name: busybox
  newName: busybox
  newTag: "1.32.0"
